/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface NexusCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bounties"
      | "createBounty"
      | "eas"
      | "externalNullifier"
      | "groupId"
      | "hasReviewed"
      | "nullifierHashes"
      | "schemaId"
      | "submitReview"
      | "worldId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyCompleted"
      | "BountyCreated"
      | "ReviewVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "eas", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "externalNullifier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "groupId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasReviewed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nullifierHashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "schemaId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitReview",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "worldId", values?: undefined): string;

  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "externalNullifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "groupId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasReviewed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nullifierHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "schemaId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "worldId", data: BytesLike): Result;
}

export namespace BountyCompletedEvent {
  export type InputTuple = [prId: BigNumberish];
  export type OutputTuple = [prId: bigint];
  export interface OutputObject {
    prId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    prId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish,
    requiredReviews: BigNumberish
  ];
  export type OutputTuple = [
    prId: bigint,
    creator: string,
    amount: bigint,
    requiredReviews: bigint
  ];
  export interface OutputObject {
    prId: bigint;
    creator: string;
    amount: bigint;
    requiredReviews: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewVerifiedEvent {
  export type InputTuple = [prId: BigNumberish, reviewer: AddressLike];
  export type OutputTuple = [prId: bigint, reviewer: string];
  export interface OutputObject {
    prId: bigint;
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NexusCore extends BaseContract {
  connect(runner?: ContractRunner | null): NexusCore;
  waitForDeployment(): Promise<this>;

  interface: NexusCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bounties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, boolean] & {
        prId: bigint;
        creator: string;
        token: string;
        amount: bigint;
        requiredReviews: bigint;
        currentReviews: bigint;
        isCompleted: boolean;
      }
    ],
    "view"
  >;

  createBounty: TypedContractMethod<
    [
      _prId: BigNumberish,
      _token: AddressLike,
      _amount: BigNumberish,
      _requiredReviews: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  eas: TypedContractMethod<[], [string], "view">;

  externalNullifier: TypedContractMethod<[], [bigint], "view">;

  groupId: TypedContractMethod<[], [bigint], "view">;

  hasReviewed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  nullifierHashes: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  schemaId: TypedContractMethod<[], [string], "view">;

  submitReview: TypedContractMethod<
    [
      _prId: BigNumberish,
      _reviewer: AddressLike,
      root: BigNumberish,
      nullifierHash: BigNumberish,
      proof: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  worldId: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, boolean] & {
        prId: bigint;
        creator: string;
        token: string;
        amount: bigint;
        requiredReviews: bigint;
        currentReviews: bigint;
        isCompleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createBounty"
  ): TypedContractMethod<
    [
      _prId: BigNumberish,
      _token: AddressLike,
      _amount: BigNumberish,
      _requiredReviews: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eas"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "externalNullifier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "groupId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasReviewed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nullifierHashes"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "schemaId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitReview"
  ): TypedContractMethod<
    [
      _prId: BigNumberish,
      _reviewer: AddressLike,
      root: BigNumberish,
      nullifierHash: BigNumberish,
      proof: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "worldId"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BountyCompleted"
  ): TypedContractEvent<
    BountyCompletedEvent.InputTuple,
    BountyCompletedEvent.OutputTuple,
    BountyCompletedEvent.OutputObject
  >;
  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewVerified"
  ): TypedContractEvent<
    ReviewVerifiedEvent.InputTuple,
    ReviewVerifiedEvent.OutputTuple,
    ReviewVerifiedEvent.OutputObject
  >;

  filters: {
    "BountyCompleted(uint256)": TypedContractEvent<
      BountyCompletedEvent.InputTuple,
      BountyCompletedEvent.OutputTuple,
      BountyCompletedEvent.OutputObject
    >;
    BountyCompleted: TypedContractEvent<
      BountyCompletedEvent.InputTuple,
      BountyCompletedEvent.OutputTuple,
      BountyCompletedEvent.OutputObject
    >;

    "BountyCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "ReviewVerified(uint256,address)": TypedContractEvent<
      ReviewVerifiedEvent.InputTuple,
      ReviewVerifiedEvent.OutputTuple,
      ReviewVerifiedEvent.OutputObject
    >;
    ReviewVerified: TypedContractEvent<
      ReviewVerifiedEvent.InputTuple,
      ReviewVerifiedEvent.OutputTuple,
      ReviewVerifiedEvent.OutputObject
    >;
  };
}
